RoutingWWidokach/Models/ErrorViewModel.cs
using System;

namespace RoutingWWidokach.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RoutingWWidokach/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RoutingWWidokach.Models;

namespace RoutingWWidokach.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RoutingWWidokach/Controllers/ThirdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RoutingWWidokach.Controllers
{
    public class ThirdController : Controller
    {
        public IActionResult Morek(string pom)
        {
            return Json(new { pom = pom });
        }
    }
}

RoutingWWidokach/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a asp-controller="Third" asp-action="Morek" asp-route-pom="dziwna nazwa" asp-fragment="fb">z atrybótow html</a>
    <a href=@Url.Action("Morek","Third")>z akcji</a>
    <a asp-route="db">z atrybutu i rotingu bez znaczniki</a>
</div>